import Head from "next/head";
import EmailJsForm from "../components/EmailJsForm";

function Contact () {
    return (
      <>
        <Head>
          <title>Wilando | Contact</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h2>Contact</h2>

        <EmailJsForm/>
      </>
    );
}

export default Contact;