import Head from "next/head"

function ForWhom () {

    return (
      <>
        <Head>
          <title>Wilando | Fro whom</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h2>Dla kogo</h2>
      </>
    );
}

export default ForWhom;