import React from "react";
import Head from "next/head";

import { search, mapImageResources } from "../src/lib/coudinary";

import CloudinaryGalery from "../components/CloudinaryGalery";

function Galery({ images, nextCursor }) {

  return (
    <>
      <Head>
        <title>Wilando | Galery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CloudinaryGalery images={images} nextCursor={nextCursor} />

    </>
  );
}

export default Galery;

export const getStaticProps = async () => {
  const results = await search();

  console.log("reults", results);

  const { resources, next_cursor: nextCursor } = results;

  const images = mapImageResources(resources);

  return {
    props: {
      images,
      nextCursor,
    },
  };
};
