import React from "react";
import Head from "next/head";

import styles from "../styles/Galery.module.css";

import CloudinaryGalery from "../components/CloudinaryGalery";

function Galery({ images }) {
  console.log(images);
  return (
    <>
      <Head>
        <title>Wilando | Galery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CloudinaryGalery />

      <h2>Galeria</h2>
      <div className={styles.images}>
        {images.map((image) => {
          return (
            <img
              key={image.id}
              alt={image.title}
              src={image.image}
              className={styles.image}
            />
          );
        })}
      </div>
    </>
  );
}

export default Galery;

export const getStaticProps = async () => {
  const results = await fetch(
    `https://api.cloudinary.com/v1_1/${process.env.CLOUDINARY_CLOUD_NAME}/resources/image`,
    {
      headers: {
        Authorization: `Basic ${Buffer.from(
          process.env.CLOUDINARY_API_KEY +
            ":" +
            process.env.CLOUDINARY_API_SECRET
        ).toString("base64")}`,
      },
    }
  ).then((r) => r.json());

  console.log("reults", results);

  const { resources } = results;

  const images = resources.map((resource) => {
    return {
      id: resource.asset_id,
      title: resource.public_id,
      image: resource.secure_url,
      width: resource.width,
      height: resource.height,
    };
  });

  return {
    props: { images },
  };
};
