import Head from "next/head";

function PriceList (){


    return (
      <>
        <Head>
          <title>Wilando | Rice list</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h2>Cennik</h2>
      </>
    );

}

export default PriceList;